---
language: node_js
node_js:
  - "10.12.0"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

install:
  - npm install -g surge

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
  - npm run prepare-deploy

deploy:
  on: master
  provider: surge
  project: ./dist/
  domain: https://local-gists.surge.sh
